// Generated by tools/gen-colliders.mjs from public/models/drone.glb: do not edit by hand.
// Drone collision shapes (Phase 2 PRD §5), model frame (m).

/** Support points of frame + stack + battery; Rapier builds their convex hull. */
export const HULL_POINTS: readonly (readonly [number, number, number])[] = [
  [0.0213, 0.1499, 0.0102],
  [-0.0234, 0.1479, 0.0496],
  [0.014, 0.1487, -0.0496],
  [0.0234, 0.1478, 0.051],
  [-0.0224, 0.1479, -0.0486],
  [0.0225, 0.1478, -0.05],
  [-0.0228, 0.1478, 0.051],
  [-0.0218, 0.1478, -0.05],
  [0.1335, 0.062, 0.1332],
  [-0.1335, 0.062, 0.1332],
  [0.1335, 0.062, -0.1332],
  [-0.1335, 0.062, -0.1332],
  [-0.1237, 0.0631, -0.1338],
  [-0.1273, 0.062, 0.134],
  [0.1273, 0.062, -0.134],
  [-0.1335, 0.058, -0.1332],
  [0.1335, 0.058, 0.1332],
  [-0.1335, 0.058, 0.1332],
  [0.1335, 0.058, -0.1332],
  [0.1273, 0.058, 0.134],
  [-0.1273, 0.058, -0.134],
  [-0.1273, 0.058, 0.134],
  [0.1273, 0.058, -0.134],
  [0.1299, 0.0571, 0.1244],
];

/** The payload canister as a capsule (axis z). */
export const PAYLOAD_CAPSULE = {
  center: [0.0002, 0.0218, -0.0491] as const,
  axis: 'z' as const,
  radius: 0.0289,
  halfLength: 0.083,
};

/** Lowest point under each motor (M1..M4): the drone lands on these. */
export const MOTOR_FEET: readonly (readonly [number, number, number])[] = [
  [0.1217, 0.0571, 0.1233],
  [0.1217, 0.0571, -0.1233],
  [-0.1217, 0.0571, 0.1233],
  [-0.1217, 0.0571, -0.1233],
];
